// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-collab/models/components"
	"net/http"
)

type AuthExchangeRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Result of the operation.
	AuthExchangeResponse *components.AuthExchangeResponse
}

func (o *AuthExchangeRequestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AuthExchangeRequestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AuthExchangeRequestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AuthExchangeRequestResponse) GetAuthExchangeResponse() *components.AuthExchangeResponse {
	if o == nil {
		return nil
	}
	return o.AuthExchangeResponse
}
