// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-collab/models/components"
	"net/http"
)

type UserRemoveRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Result of the operation.
	UserRemoveResponse *components.UserRemoveResponse
}

func (o *UserRemoveRequestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UserRemoveRequestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UserRemoveRequestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UserRemoveRequestResponse) GetUserRemoveResponse() *components.UserRemoveResponse {
	if o == nil {
		return nil
	}
	return o.UserRemoveResponse
}
