// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartResponse struct {
	// AuthID is the unique ID of the auth flow. To complete the auth flow, the `authId` will also be used for the
	// AuthFinish request.
	AuthID string `json:"authId"`
	// AuthToken is a bearer token for use by the Prove Auth SDK.
	AuthToken string `json:"authToken"`
	// PushTokens is an array of Push Tokens for the customer to use to initiate push notifications via their own service.
	PushTokens []PushToken `json:"pushTokens,omitempty"`
}

func (o *AuthStartResponse) GetAuthID() string {
	if o == nil {
		return ""
	}
	return o.AuthID
}

func (o *AuthStartResponse) GetAuthToken() string {
	if o == nil {
		return ""
	}
	return o.AuthToken
}

func (o *AuthStartResponse) GetPushTokens() []PushToken {
	if o == nil {
		return nil
	}
	return o.PushTokens
}
