// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjects struct {
	Device *AuthStartRequestSubjectDevice `json:"device,omitempty"`
	Mobile *AuthStartRequestSubjectMobile `json:"mobile,omitempty"`
	User   *AuthStartRequestSubjectUser   `json:"user,omitempty"`
}

func (o *AuthStartRequestSubjects) GetDevice() *AuthStartRequestSubjectDevice {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *AuthStartRequestSubjects) GetMobile() *AuthStartRequestSubjectMobile {
	if o == nil {
		return nil
	}
	return o.Mobile
}

func (o *AuthStartRequestSubjects) GetUser() *AuthStartRequestSubjectUser {
	if o == nil {
		return nil
	}
	return o.User
}
