// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestDelivery struct {
	Push AuthStartRequestDeliveryPush `json:"push"`
}

func (o *AuthStartRequestDelivery) GetPush() AuthStartRequestDeliveryPush {
	if o == nil {
		return AuthStartRequestDeliveryPush{}
	}
	return o.Push
}
