// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobileAuthenticators struct {
	Instant *AuthStartRequestSubjectMobileAuthenticatorInstant `json:"instant,omitempty"`
	Otp     *AuthStartRequestSubjectMobileAuthenticatorOTP     `json:"otp,omitempty"`
	Passive *AuthStartRequestSubjectMobileAuthenticatorPassive `json:"passive,omitempty"`
}

func (o *AuthStartRequestSubjectMobileAuthenticators) GetInstant() *AuthStartRequestSubjectMobileAuthenticatorInstant {
	if o == nil {
		return nil
	}
	return o.Instant
}

func (o *AuthStartRequestSubjectMobileAuthenticators) GetOtp() *AuthStartRequestSubjectMobileAuthenticatorOTP {
	if o == nil {
		return nil
	}
	return o.Otp
}

func (o *AuthStartRequestSubjectMobileAuthenticators) GetPassive() *AuthStartRequestSubjectMobileAuthenticatorPassive {
	if o == nil {
		return nil
	}
	return o.Passive
}
