// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponseSubjectMobileResult struct {
	Error   *AuthFinishResponseError                      `json:"error,omitempty"`
	Success *AuthFinishResponseSubjectMobileResultSuccess `json:"success,omitempty"`
}

func (o *AuthFinishResponseSubjectMobileResult) GetError() *AuthFinishResponseError {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *AuthFinishResponseSubjectMobileResult) GetSuccess() *AuthFinishResponseSubjectMobileResultSuccess {
	if o == nil {
		return nil
	}
	return o.Success
}
