// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthContinueResponseSubjectCardResult struct {
	Error   *AuthContinueResponseError `json:"error,omitempty"`
	Success *bool                      `json:"success,omitempty"`
}

func (o *AuthContinueResponseSubjectCardResult) GetError() *AuthContinueResponseError {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *AuthContinueResponseSubjectCardResult) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}
