// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponseSubjectDeviceResultSuccessClaim struct {
	// DeviceID is the unique ID of the device.
	DeviceID string `json:"deviceId"`
}

func (o *AuthFinishResponseSubjectDeviceResultSuccessClaim) GetDeviceID() string {
	if o == nil {
		return ""
	}
	return o.DeviceID
}
