// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthContinueResponseSubjectMobileResult struct {
	Error *AuthContinueResponseError `json:"error,omitempty"`
	// Success will be true if the bind was successful.
	Success bool `json:"success"`
}

func (o *AuthContinueResponseSubjectMobileResult) GetError() *AuthContinueResponseError {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *AuthContinueResponseSubjectMobileResult) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
