// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectDevice struct {
	Authenticators *AuthStartRequestSubjectDeviceAuthenticators `json:"authenticators,omitempty"`
}

func (o *AuthStartRequestSubjectDevice) GetAuthenticators() *AuthStartRequestSubjectDeviceAuthenticators {
	if o == nil {
		return nil
	}
	return o.Authenticators
}
