// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponseScanDeliveryExtras struct {
	OriginatingIPGeolocation *string `json:"originatingIpGeolocation,omitempty"`
}

func (o *AuthFinishResponseScanDeliveryExtras) GetOriginatingIPGeolocation() *string {
	if o == nil {
		return nil
	}
	return o.OriginatingIPGeolocation
}
