// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthContinueRequestSubjectMobile struct {
	Claim *AuthContinueRequestSubjectMobileClaim `json:"claim,omitempty"`
}

func (o *AuthContinueRequestSubjectMobile) GetClaim() *AuthContinueRequestSubjectMobileClaim {
	if o == nil {
		return nil
	}
	return o.Claim
}
