// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/test-collab/internal/utils"
)

type AuthContinueRequest struct {
	// AuthID is the unique ID of the auth flow to continue.
	AuthID string `json:"authId"`
	// RequestID is a UUID generated on the customer side to be associated with the unique request for tracking.
	// Acceptable characters are: alphanumeric with symbols '-._+=/'.
	RequestID *string                     `default:"eba12f3a-5555-47bc-b85d-21c0cbc4b973" json:"requestId"`
	Subjects  AuthContinueRequestSubjects `json:"subjects"`
}

func (a AuthContinueRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthContinueRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AuthContinueRequest) GetAuthID() string {
	if o == nil {
		return ""
	}
	return o.AuthID
}

func (o *AuthContinueRequest) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AuthContinueRequest) GetSubjects() AuthContinueRequestSubjects {
	if o == nil {
		return AuthContinueRequestSubjects{}
	}
	return o.Subjects
}
