// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthContinueResponse struct {
	Subjects AuthContinueResponseSubjectsResults `json:"subjects"`
}

func (o *AuthContinueResponse) GetSubjects() AuthContinueResponseSubjectsResults {
	if o == nil {
		return AuthContinueResponseSubjectsResults{}
	}
	return o.Subjects
}
