// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobile struct {
	Authenticators *AuthStartRequestSubjectMobileAuthenticators `json:"authenticators,omitempty"`
	Claim          *AuthStartRequestSubjectMobileClaim          `json:"claim,omitempty"`
}

func (o *AuthStartRequestSubjectMobile) GetAuthenticators() *AuthStartRequestSubjectMobileAuthenticators {
	if o == nil {
		return nil
	}
	return o.Authenticators
}

func (o *AuthStartRequestSubjectMobile) GetClaim() *AuthStartRequestSubjectMobileClaim {
	if o == nil {
		return nil
	}
	return o.Claim
}
