// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobileClaim struct {
	// MobileNumber will be used when performing OTP fallback and will not use the optional value provided by the SDK.
	// Mobile number may be prefixed with a plus sign, but does not need to be for US. A plus sign is required for
	// international.
	MobileNumber *string `json:"mobileNumber,omitempty"`
}

func (o *AuthStartRequestSubjectMobileClaim) GetMobileNumber() *string {
	if o == nil {
		return nil
	}
	return o.MobileNumber
}
