// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponseSubjectMobileResultSuccessExtras struct {
	// MobileCountryCode is the country code of the mobile number.
	MobileCountryCode *string `json:"mobileCountryCode,omitempty"`
	// MobileOperatorName is the name of the mobile network operator of the mobile number.
	MobileOperatorName *string `json:"mobileOperatorName,omitempty"`
	// PayfoneAlias is the Prove alias of the mobile number.
	PayfoneAlias *string `json:"payfoneAlias,omitempty"`
}

func (o *AuthFinishResponseSubjectMobileResultSuccessExtras) GetMobileCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.MobileCountryCode
}

func (o *AuthFinishResponseSubjectMobileResultSuccessExtras) GetMobileOperatorName() *string {
	if o == nil {
		return nil
	}
	return o.MobileOperatorName
}

func (o *AuthFinishResponseSubjectMobileResultSuccessExtras) GetPayfoneAlias() *string {
	if o == nil {
		return nil
	}
	return o.PayfoneAlias
}
