// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectDeviceAuthenticatorPassive struct {
	// AllowPasscodeFallback specifies whether passcode is allowed as a fallback protection for device in-app step-up keys.
	AllowPasscodeFallback *bool `json:"allowPasscodeFallback,omitempty"`
	// UserVerificationLevel accepts 'required', 'preferred' or 'discouraged' as a value to specify biometric verification with FIDO.
	UserVerificationLevel *string `json:"userVerificationLevel,omitempty"`
}

func (o *AuthStartRequestSubjectDeviceAuthenticatorPassive) GetAllowPasscodeFallback() *bool {
	if o == nil {
		return nil
	}
	return o.AllowPasscodeFallback
}

func (o *AuthStartRequestSubjectDeviceAuthenticatorPassive) GetUserVerificationLevel() *string {
	if o == nil {
		return nil
	}
	return o.UserVerificationLevel
}
