// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthContinueRequestSubjects struct {
	Mobile *AuthContinueRequestSubjectMobile `json:"mobile,omitempty"`
}

func (o *AuthContinueRequestSubjects) GetMobile() *AuthContinueRequestSubjectMobile {
	if o == nil {
		return nil
	}
	return o.Mobile
}
