// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthContinueResponseSubjectsResults struct {
	Card   *AuthContinueResponseSubjectCardResult   `json:"card,omitempty"`
	Mobile *AuthContinueResponseSubjectMobileResult `json:"mobile,omitempty"`
}

func (o *AuthContinueResponseSubjectsResults) GetCard() *AuthContinueResponseSubjectCardResult {
	if o == nil {
		return nil
	}
	return o.Card
}

func (o *AuthContinueResponseSubjectsResults) GetMobile() *AuthContinueResponseSubjectMobileResult {
	if o == nil {
		return nil
	}
	return o.Mobile
}
