// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectUser struct {
	Authenticators AuthStartRequestSubjectUserAuthenticators `json:"authenticators"`
	Claim          AuthStartRequestSubjectUserClaim          `json:"claim"`
}

func (o *AuthStartRequestSubjectUser) GetAuthenticators() AuthStartRequestSubjectUserAuthenticators {
	if o == nil {
		return AuthStartRequestSubjectUserAuthenticators{}
	}
	return o.Authenticators
}

func (o *AuthStartRequestSubjectUser) GetClaim() AuthStartRequestSubjectUserClaim {
	if o == nil {
		return AuthStartRequestSubjectUserClaim{}
	}
	return o.Claim
}
