// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponseSubjects struct {
	// swaggerIGNORE:model AuthFinishResponseSubjectCardsResult
	Card   *SubjectCardResult                     `json:"card,omitempty"`
	Device *AuthFinishResponseSubjectDeviceResult `json:"device,omitempty"`
	Mobile *AuthFinishResponseSubjectMobileResult `json:"mobile,omitempty"`
}

func (o *AuthFinishResponseSubjects) GetCard() *SubjectCardResult {
	if o == nil {
		return nil
	}
	return o.Card
}

func (o *AuthFinishResponseSubjects) GetDevice() *AuthFinishResponseSubjectDeviceResult {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *AuthFinishResponseSubjects) GetMobile() *AuthFinishResponseSubjectMobileResult {
	if o == nil {
		return nil
	}
	return o.Mobile
}
