// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponsePushDelivery struct {
	Extras   *AuthFinishResponsePushDeliveryExtras `json:"extras,omitempty"`
	Response *string                               `json:"response,omitempty"`
}

func (o *AuthFinishResponsePushDelivery) GetExtras() *AuthFinishResponsePushDeliveryExtras {
	if o == nil {
		return nil
	}
	return o.Extras
}

func (o *AuthFinishResponsePushDelivery) GetResponse() *string {
	if o == nil {
		return nil
	}
	return o.Response
}
