// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthFinishResponseSubjectDeviceResultSuccess struct {
	Claim *AuthFinishResponseSubjectDeviceResultSuccessClaim `json:"claim,omitempty"`
	// CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
	CreatedAt *int64                                              `json:"createdAt,omitempty"`
	Extras    *AuthFinishResponseSubjectDeviceResultSuccessExtras `json:"extras,omitempty"`
	// UserVerificationLevel is the level that was performed during device passive authentication.
	UvLevel *int64 `json:"uvLevel,omitempty"`
}

func (o *AuthFinishResponseSubjectDeviceResultSuccess) GetClaim() *AuthFinishResponseSubjectDeviceResultSuccessClaim {
	if o == nil {
		return nil
	}
	return o.Claim
}

func (o *AuthFinishResponseSubjectDeviceResultSuccess) GetCreatedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *AuthFinishResponseSubjectDeviceResultSuccess) GetExtras() *AuthFinishResponseSubjectDeviceResultSuccessExtras {
	if o == nil {
		return nil
	}
	return o.Extras
}

func (o *AuthFinishResponseSubjectDeviceResultSuccess) GetUvLevel() *int64 {
	if o == nil {
		return nil
	}
	return o.UvLevel
}
