// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectUserClaim struct {
	// Provided if true, registers the user ID with a device, otherwise it valids the user ID.
	Provided *bool `json:"provided,omitempty"`
	// UserID is a user identifier generated on the customer side to be associated with a device.
	// Acceptable characters are: alphanumeric with symbols '-._+=/:'.
	UserID string `json:"userId"`
}

func (o *AuthStartRequestSubjectUserClaim) GetProvided() *bool {
	if o == nil {
		return nil
	}
	return o.Provided
}

func (o *AuthStartRequestSubjectUserClaim) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
