// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AuthStartRequestSubjectDeviceAuthenticators struct {
	Passive *AuthStartRequestSubjectDeviceAuthenticatorPassive `json:"passive,omitempty"`
}

func (o *AuthStartRequestSubjectDeviceAuthenticators) GetPassive() *AuthStartRequestSubjectDeviceAuthenticatorPassive {
	if o == nil {
		return nil
	}
	return o.Passive
}
