// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/test-collab/internal/utils"
)

type DeviceUnregisterRequest struct {
	// DeviceID is the UUID of the device to unregister.
	DeviceID string `json:"deviceId"`
	// RequestID is a UUID generated on the customer side to be associated with the unique request for tracking.
	// Acceptable characters are: alphanumeric with symbols '-._+=/'.
	RequestID *string `default:"eba12f3a-5555-47bc-b85d-21c0cbc4b973" json:"requestId"`
}

func (d DeviceUnregisterRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeviceUnregisterRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DeviceUnregisterRequest) GetDeviceID() string {
	if o == nil {
		return ""
	}
	return o.DeviceID
}

func (o *DeviceUnregisterRequest) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
