// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type PushToken struct {
	// DeviceID is the UUID of the device where the push message will be sent.
	DeviceID string `json:"deviceId"`
	// Platform is the platform of the device were the push message will be received. Possible values: ios, android,
	// and web.
	Platform string `json:"platform"`
	// PushToken is the push token to use when sending a push message to the user.
	PushToken string `json:"pushToken"`
	// RegistrationTimestamp is the timestamp when the push token was associated with the device. The field is in Unix
	// time which is the number of seconds elapsed since January 1, 1970 UTC.
	RegistrationTimestamp int64 `json:"registrationTimestamp"`
}

func (o *PushToken) GetDeviceID() string {
	if o == nil {
		return ""
	}
	return o.DeviceID
}

func (o *PushToken) GetPlatform() string {
	if o == nil {
		return ""
	}
	return o.Platform
}

func (o *PushToken) GetPushToken() string {
	if o == nil {
		return ""
	}
	return o.PushToken
}

func (o *PushToken) GetRegistrationTimestamp() int64 {
	if o == nil {
		return 0
	}
	return o.RegistrationTimestamp
}
