// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/test-collab/internal/utils"
)

type PushTokenDeleteRequest struct {
	// Devices is an array of UUIDs of the devices to delete push tokens.
	Devices []string `json:"devices"`
	// RequestID is a UUID generated on the customer side to be associated with the unique request for tracking.
	// Acceptable characters are: alphanumeric with symbols '-._+=/'.
	RequestID *string `default:"eba12f3a-5555-47bc-b85d-21c0cbc4b973" json:"requestId"`
}

func (p PushTokenDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PushTokenDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PushTokenDeleteRequest) GetDevices() []string {
	if o == nil {
		return []string{}
	}
	return o.Devices
}

func (o *PushTokenDeleteRequest) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
