// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// SubjectCardResultSuccess - swaggerIGNORE:model AuthFinishResponseSubjectCardResultSuccess
type SubjectCardResultSuccess struct {
	AuthenticatorType *string `json:"authenticatorType,omitempty"`
	// swaggerIGNORE:model AuthFinishResponseSubjectCardResultSuccessClaim
	Claim *SubjectCardResultSuccessClaim `json:"claim,omitempty"`
	// CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
	CreatedAt *int64 `json:"createdAt,omitempty"`
}

func (o *SubjectCardResultSuccess) GetAuthenticatorType() *string {
	if o == nil {
		return nil
	}
	return o.AuthenticatorType
}

func (o *SubjectCardResultSuccess) GetClaim() *SubjectCardResultSuccessClaim {
	if o == nil {
		return nil
	}
	return o.Claim
}

func (o *SubjectCardResultSuccess) GetCreatedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}
