// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type SubjectDeviceResultSuccessExtrasTrust struct {
	// ReasonCodes contains a list of the reason codes detected on the device.
	ReasonCodes []int64 `json:"reasonCodes,omitempty"`
}

func (o *SubjectDeviceResultSuccessExtrasTrust) GetReasonCodes() []int64 {
	if o == nil {
		return nil
	}
	return o.ReasonCodes
}
