// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// SubjectCardResult - swaggerIGNORE:model AuthFinishResponseSubjectCardsResult
type SubjectCardResult struct {
	Error *AuthFinishResponseCardError `json:"error,omitempty"`
	// swaggerIGNORE:model AuthFinishResponseSubjectCardResultSuccess
	Success *SubjectCardResultSuccess `json:"success,omitempty"`
}

func (o *SubjectCardResult) GetError() *AuthFinishResponseCardError {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *SubjectCardResult) GetSuccess() *SubjectCardResultSuccess {
	if o == nil {
		return nil
	}
	return o.Success
}
