// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// SubjectCardResultSuccessClaim - swaggerIGNORE:model AuthFinishResponseSubjectCardResultSuccessClaim
type SubjectCardResultSuccessClaim struct {
	Puid *string `json:"puid,omitempty"`
}

func (o *SubjectCardResultSuccessClaim) GetPuid() *string {
	if o == nil {
		return nil
	}
	return o.Puid
}
