// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/test-collab/internal/utils"
)

type UserUnbindRequest struct {
	// DeviceID is the UUID of the device to disassociate from the user ID. If no device is specified, all devices
	// associated with the user ID will be unbound.
	DeviceID *string `json:"deviceId,omitempty"`
	// RequestID is a UUID generated on the customer side to be associated with the unique request for tracking.
	// Acceptable characters are: alphanumeric with symbols '-._+=/'.
	RequestID *string `default:"eba12f3a-5555-47bc-b85d-21c0cbc4b973" json:"requestId"`
	// UserID is a user identifier generated on the customer side to remove association with a device.
	// Acceptable characters are: alphanumeric with symbols '-._+=/:'.
	UserID string `json:"userId"`
}

func (u UserUnbindRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserUnbindRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UserUnbindRequest) GetDeviceID() *string {
	if o == nil {
		return nil
	}
	return o.DeviceID
}

func (o *UserUnbindRequest) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *UserUnbindRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
