// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/test-collab/models/sdkerrors"
)

type UserUnbindResponse struct {
	Error   *sdkerrors.Error `json:"error,omitempty"`
	Success *bool            `json:"success,omitempty"`
}

func (o *UserUnbindResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *UserUnbindResponse) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}
